# Generated by Django 2.1.1 on 2018-09-14 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0003_auto_20180912_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_form',
            name='pincode',
            field=models.CharField(max_length=6),
        ),
    ]
