# Generated by Django 2.1.1 on 2018-09-14 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0004_auto_20180914_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_form',
            name='pincode',
            field=models.CharField(max_length=20),
        ),
    ]
