# Generated by Django 2.1.1 on 2018-09-14 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0005_auto_20180914_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_form',
            name='pincode',
            field=models.IntegerField(),
        ),
    ]
