# Generated by Django 2.1.1 on 2018-09-17 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0006_auto_20180914_0902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_form',
            old_name='address',
            new_name='adddress',
        ),
        migrations.RenameField(
            model_name='company_form',
            old_name='city',
            new_name='citsy',
        ),
        migrations.RenameField(
            model_name='company_form',
            old_name='discription',
            new_name='discrsiption',
        ),
        migrations.RenameField(
            model_name='company_form',
            old_name='email',
            new_name='emaisl',
        ),
        migrations.RenameField(
            model_name='company_form',
            old_name='name',
            new_name='passsword',
        ),
        migrations.RenameField(
            model_name='company_form',
            old_name='pincode',
            new_name='pincsode',
        ),
        migrations.RenameField(
            model_name='company_form',
            old_name='password',
            new_name='pname',
        ),
        migrations.RenameField(
            model_name='company_form',
            old_name='title',
            new_name='tditle',
        ),
        migrations.RenameField(
            model_name='company_form',
            old_name='url',
            new_name='ursl',
        ),
    ]
